/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_thingsbook_it_LibGit2 */
#ifndef _Included_com_thingsbook_it_LibGit2
#define _Included_com_thingsbook_it_LibGit2
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_thingsbook_it_LibGit2
 * Method:    clone
 * Signature: (Ljava/lang/String;Ljava/lang/String)I
 */
JNIEXPORT jint JNICALL Java_com_thingsbook_it_LibGit2_clone
(JNIEnv *, jclass, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
